-- 组织机构
insert into moyu.sys_org (id, code, name, parent_code, org_type, org_level, org_path, sort_num, status, ext_json, remark, deleted, create_time, create_by, update_time, update_by)
values
    (2001, '10000000', 'MY集团', '0', 1, 1, '0', 1, 0, null, null, 0, null, null, null, null),
    (2002, '11000000', '集团总部', '10000000', 1, 2, '10000000,0', 2, 0, null, null, 0, null, null, null, null),
    (2003, '12000000', '北京公司', '10000000', 1, 2, '10000000,0', 4, 0, null, null, 0, null, null, null, null),
    (2004, '14000000', '华东公司', '10000000', 1, 2, '10000000,0', 6, 0, null, null, 0, null, null, null, null),
    (2005, '16000000', '华南公司', '10000000', 1, 2, '10000000,0', 8, 0, null, null, 0, null, null, null, null),
    (2006, '11001000', '总部财务部', '11000000', 2, 2, '11000000,10000000,0', 22, 0, null, null, 0, null, null, null, null),
    (2007, '11002000', '总部科技部', '11000000', 2, 2, '11000000,10000000,0', 24, 0, null, null, 0, null, null, null, null),
    (2008, '12001000', '北京运营部', '12000000', 2, 2, '12000000,10000000,0', 42, 0, null, null, 0, null, null, null, null),
    (2009, '12002000', '北京技术部', '12000000', 2, 2, '12000000,10000000,0', 44, 0, null, null, 0, null, null, null, null),
    (2010, '14001000', '华东技术部', '14000000', 2, 2, '14000000,10000000,0', 62, 0, null, null, 0, null, null, null, null),
    (2011, '16001000', '华南行政部', '16000000', 2, 2, '16000000,10000000,0', 84, 0, null, null, 0, null, null, null, null);

-- 用户
insert into moyu.sys_user (user_id, account, password, nick_name, avatar, name, gender, birthday, email, phone, id_no, address, staff_code, entry_date, org_code, org_name, org_path, login_ip, login_time, last_login_ip, last_login_time, pwd_update_time, status, remark, deleted, create_time, create_by, update_time, update_by)
values  ('202602121001', 'superAdmin', '255a58278b06e24018d1f042e8657ea3', null, null, '超管小李', 1, null, null, null, null, null, null, null, '11000000', '集团总部', '11000000,10000000,0', null, null, null, null, null, 0, null, 0, null, null, null, null),
        ('202602121002', 'rAdmin', '255a58278b06e24018d1f042e8657ea3', null, null, '超管小王', 1, null, null, null, null, null, null, null, '12000000', '北京公司', '12000000,10000000,0', null, null, null, null, null, 0, null, 0, null, null, null, null),
        ('202602121003', 'bjAdmin', '255a58278b06e24018d1f042e8657ea3', null, null, 'bjAdmin', 1, null, null, null, null, null, null, null, '12000000', '北京公司', '12000000,10000000,0', null, null, null, null, null, 0, null, 0, null, null, null, null),
        ('202602121004', 'auditor', '255a58278b06e24018d1f042e8657ea3', null, null, '审计员小王', 1, null, null, null, null, null, null, null, '11000000', '集团总部', '11000000,10000000,0', null, null, null, null, null, 0, null, 0, null, null, null, null);

-- 角色
insert into moyu.sys_role (id, code, name, sort_num, status, ext_json, remark, deleted, create_time, create_by, update_time, update_by)
values (100, 'r_default', ' 默认角色 ', 1, 0, null, '', 0, null, null, null, null),
       (110, 'ROOT', 'ROOT 管理员 ', 1, 0, null, '', 0, null, null, null, null),
       (120, 'r_superAdmin', ' 超级管理员 ', 2, 0, null, null, 0, null, null, null, null),
       (130, 'r_roleAdmin', ' 角色管理员 ', 3, 0, null, '', 0, null, null, null, null),
       (140, 'r_orgAdmin', ' 公司管理员 ', 4, 0, null, '', 0, null, null, null, null),
       (150, 'r_auditor', ' 审计员 ', 5, 0, null, '', 0, null, null, null, null);

-- 功能权限组
insert into moyu.sys_group (id, code, name, org_code, org_name, org_path, sort_num, status, ext_json, remark, deleted, create_time, create_by, update_time, update_by)
values  (1894925631903645700, 'g_zongbu', '总部管理岗', '11000000', '集团总部', '11000000,10000000,0', 2, 0, null, null, 0, null, null, null, null),
        (1894925631903645701, 'g_beijing', '北京公司管理岗', '12000000', '北京公司', '12000000,10000000,0', 9, 0, null, null, 0, null, null, null, null),
        (1894925631903645702, 'g_auditor', '全局审计岗', '10000000', 'MY集团', '10000000,0', 5, 0, null, null, 0, null, null, null, null);

-- 菜单数据
insert into moyu.sys_resource (code, name, parent_code, resource_type, path, component, permission, icon, visible, module, sort_num, ext_json, remark, deleted, create_time, create_by, update_time, update_by)
values  ('sys_module', '系统模块', '0', 1, '/sysModule', 'Layout', '', 'appstore-add-outlined', 1, 'sys_module', 1, null, '', 0, null, null, null, null),
        ('biz_module', '业务模块', '0', 1, '/bizModule', 'Layout', '', 'profile-outlined', 1, null, 2, null, '', 0, null, null, null, null),

        ('dir_sys_org', '组织架构', 'sys_module', 2, '/org', null, '', 'apartment-outlined', 1, 'sys_module', 10, null, '', 0, null, null, null, null),
        ('dir_sys_perm', '权限控制', 'sys_module', 2, '/perm', null, '', 'unlock-outlined', 1, 'sys_module', 20, null, '', 0, null, null, null, null),
        ('dir_sys_resource', '资源管理', 'sys_module', 2, '/resource', null, null, 'trademark-circle-outlined', 1, 'sys_module', 30, null, null, 0, null, null, null, null),
        ('dir_sys_dev', '系统工具', 'sys_module', 2, '/dev', null, '', 'tool-outlined', 1, 'sys_module', 40, null, '', 0, null, null, null, null),
        ('dir_sys_ops', '系统运维', 'sys_module', 2, '/ops', null, '', 'hdd-outlined', 1, 'sys_module', 50, null, '', 0, null, null, null, null),
        ('dir_sys_mobile', '移动端管理', 'sys_module', 2, '/mobile', null, '', 'mobile-outlined', 1, 'sys_module', 60, null, '', 0, null, null, null, null),
        ('dir_sys_common', '通用资源', 'sys_module', 2, '/sys/common', null, '', 'folder-open-outlined', 0, 'sys_module', 100, null, '', 0, null, null, null, null),
        ('dir_biz_company', '公司架构', 'biz_module', 2, '/biz/co', null, '', 'cluster-outlined', 1, 'biz_module', 20, null, '', 0, null, null, null, null),
        ('menu_biz_notice', '通知公告', 'biz_module', 3, '/biz/notice', 'biz/notice/index', null, 'appstore-outlined', 1, 'biz_module', 30, null, '', 0, null, null, null, null),

        ('menu_sys_org', '组织管理', 'dir_sys_org', 3, '/sys/org', 'system/org/index', null, 'cluster-outlined', 1, 'sys_module', 1010, null, '', 0, null, null, null, null),
        ('menu_sys_user', '用户管理', 'dir_sys_org', 3, '/sys/user', 'system/user/index', '', 'user-outlined', 1, 'sys_module', 1020, null, '', 0, null, null, null, null),
        ('menu_sys_group', '岗位权限', 'dir_sys_perm', 3, '/sys/group', 'system/group/index', '', 'team-outlined', 1, 'sys_module', 2010, null, '', 0, null, null, null, null),
        ('menu_sys_role', '角色管理', 'dir_sys_perm', 3, '/sys/role', 'system/role/index', '', 'deployment-unit-outlined', 1, 'sys_module', 2020, null, '', 0, null, null, null, null),
        ('menu_sys_module', '模块管理', 'dir_sys_resource', 3, '/sys/module', 'system/resource/module/index', '', 'appstore-add-outlined', 1, 'sys_module', 3010, null, '', 0, null, null, null, null),
        ('menu_sys_menu', '菜单管理', 'dir_sys_resource', 3, '/sys/menu', 'system/resource/menu/index', '', 'pic-left-outlined', 1, 'sys_module', 3020, null, '', 0, null, null, null, null),
        ('menu_sys_api', '接口管理', 'dir_sys_resource', 3, '/sys/api', 'system/resource/api/index', '', 'api-outlined', 1, 'sys_module', 3030, null, null, 0, null, null, null, null),
        ('menu_sys_resource', '资源查询', 'dir_sys_resource', 3, '/sys/resource', 'system/resource/index', '', 'unordered-list-outlined', 1, 'sys_module', 3040, null, null, 0, null, null, null, null),

        ('menu_sys_gen', '代码生成', 'dir_sys_dev', 3, '/dev/gen', 'dev/gen/index', '', 'code-outlined', 1, 'sys_module', 4010, null, '', 0, null, null, null, null),
        ('menu_sys_file', '文件管理', 'dir_sys_dev', 3, '/dev/file/index', 'dev/file/index', null, 'copy-outlined', 1, 'sys_module', 4020, null, '', 0, null, null, null, null),
        ('menu_sys_sms', '短信发送', 'dir_sys_dev', 3, '/dev/sms/index', 'dev/sms/index', null, 'mail-outlined', 1, 'sys_module', 4030, null, '', 0, null, null, null, null),
        ('menu_sys_email', '消息推送', 'dir_sys_dev', 3, '/dev/push/index', 'dev/push/index', null, 'send-outlined', 1, 'sys_module', 4040, null, '', 0, null, null, null, null),
        ('menu_sys_message', '站内信', 'dir_sys_dev', 3, '/dev/message/index', 'dev/message/index', null, 'message-outlined', 1, 'sys_module', 4050, null, '', 0, null, null, null, null),

        ('menu_sys_session', '会话管理', 'dir_sys_ops', 3, '/auth/monitor', 'auth/monitor/index', null, 'bars-outlined', 1, 'sys_module', 5002, null, '', 0, null, null, null, null),
        ('menu_sys_seq', '序列器', 'dir_sys_ops', 3, '/dev/seq', 'dev/seq/index', null, 'field-number-outlined', 1, 'sys_module', 5003, null, '', 0, null, null, null, null),
        ('menu_sys_config', '系统配置', 'dir_sys_ops', 3, '/sys/config', 'system/config/index', null, 'cloud-server-outlined', 1, 'sys_module', 5010, null, '', 0, null, null, null, null),
        ('menu_sys_job', '任务调度', 'dir_sys_ops', 3, '/dev/job', 'dev/job/index', null, 'field-time-outlined', 1, 'sys_module', 5020, null, '', 0, null, null, null, null),
        ('menu_sys_third', '三方用户', 'dir_sys_ops', 3, '/auth/third', 'auth/third/index', null, 'team-outlined', 1, 'sys_module', 5030, null, '', 0, null, null, null, null),
        ('iframe_sys_link', '内部链接', 'dir_sys_ops', 4, 'https://www.baidu.com', '', '', 'link-outlined', 1, 'sys_module', 5040, null, '', 0, null, null, null, null),
        ('link_sys_doc', '外部链接', 'dir_sys_ops', 5, 'https://www.baidu.com', '', '', 'disconnect-outlined', 1, 'sys_module', 5050, null, '', 0, null, null, null, null),
        ('dir_sys_log', '日志审计', 'dir_sys_ops', 2, '/ops/log', null, null, 'file-search-outlined', 1, 'sys_module', 5060, null, '', 0, null, null, null, null),
        ('menu_sys_log', '系统日志', 'dir_sys_log', 3, '/ops/sys/log', 'system/log/index', null, 'bars-outlined', 1, 'sys_module', 5063, null, '', 0, null, null, null, null),
        ('menu_sys_vislog', '访问日志', 'dir_sys_log', 3, '/ops/log/vislog', 'system/log/visLog', null, 'bars-outlined', 1, 'sys_module', 5061, null, '', 0, null, null, null, null),
        ('menu_sys_oplog', '操作日志', 'dir_sys_log', 3, '/ops/log/oplog', 'system/log/opLog', null, 'bars-outlined', 1, 'sys_module', 5062, null, '', 0, null, null, null, null),
        ('menu_sys_mobile_module', '模块管理', 'dir_sys_mobile', 3, '/mobile/module/index', 'mobile/resource/module/index', null, 'build-outlined', 1, 'sys_module', 51, null, '', 0, null, null, null, null),
        ('menu_sys_mobile_menu', '菜单管理', 'dir_sys_mobile', 3, '/mobile/menu/index', 'mobile/resource/menu/index', null, 'appstore-add-outlined', 1, 'sys_module', 52, null, '', 0, null, null, null, null),
        ('menu_biz_org', '机构管理', 'dir_biz_company', 3, '/biz/org', 'biz/org/index', null, 'cluster-outlined', 1, 'biz_module', 52, null, '', 0, null, null, null, null),
        ('menu_biz_user', '人员管理', 'dir_biz_company', 3, '/biz/user', 'biz/user/index', null, 'user-outlined', 1, 'biz_module', 53, null, '', 0, null, null, null, null),
        ('menu_biz_pos', '岗位管理', 'dir_biz_company', 3, '/biz/position', 'biz/position/index', null, 'apartment-outlined', 1, 'biz_module', 54, null, '', 0, null, null, null, null),

        ('api_sys_org_tree', '组织树', 'dir_sys_common', 6, null, '', 'sys:org:tree', null, 1, 'sys_module', 101006, null, null, 0, null, null, null, null),
        ('btn_sys_org_add', '新增组织', 'menu_sys_org', 6, null, '', 'sys:org:add', '', 0, 'sys_module', 101001, null, '', 0, null, null, null, null),
        ('btn_sys_org_delete', '删除组织', 'menu_sys_org', 6, null, '', 'sys:org:delete', '', 0, 'sys_module', 101002, null, '', 0, null, null, null, null),
        ('btn_sys_org_edit', '修改组织', 'menu_sys_org', 6, null, '', 'sys:org:edit', '', 0, 'sys_module', 101003, null, '', 0, null, null, null, null),
        ('btn_sys_org_list', '组织列表', 'menu_sys_org', 6, null, '', 'sys:org:page', '', 1, 'sys_module', 101004, null, '', 0, null, null, null, null),
        ('btn_sys_org_detail', '组织详情', 'menu_sys_org', 6, null, '', 'sys:org:detail', null, 0, 'sys_module', 101005, null, null, 0, null, null, null, null),
        ('btn_sys_org_deleteTree', '删除组织树', 'menu_sys_org', 6, null, '', 'sys:org:deleteTree', null, 0, 'sys_module', 101007, null, null, 0, null, null, null, null),

        ('btn_sys_user_add', '新增用户', 'menu_sys_user', 6, null, '', 'sys:user:add', null, 0, 'sys_module', 102001, null, null, 0, null, null, null, null),
        ('btn_sys_user_delete', '删除用户', 'menu_sys_user', 6, null, '', 'sys:user:delete', null, 0, 'sys_module', 102002, null, null, 0, null, null, null, null),
        ('btn_sys_user_edit', '修改用户', 'menu_sys_user', 6, null, '', 'sys:user:edit', null, 0, 'sys_module', 102003, null, null, 0, null, null, null, null),
        ('btn_sys_user_list', '用户列表', 'menu_sys_user', 6, null, '', 'sys:user:page', null, 1, 'sys_module', 102004, null, null, 0, null, null, null, null),
        ('btn_sys_user_detail', '用户详情', 'menu_sys_user', 6, null, '', 'sys:user:detail', null, 0, 'sys_module', 102005, null, null, 0, null, null, null, null),

        ('btn_sys_group_add', '新增岗位', 'menu_sys_group', 6, null, '', 'sys:group:add', null, 0, 'sys_module', 201001, null, null, 0, null, null, null, null),
        ('btn_sys_group_delete', '删除岗位', 'menu_sys_group', 6, null, '', 'sys:group:delete', null, 0, 'sys_module', 201002, null, null, 0, null, null, null, null),
        ('btn_sys_group_edit', '修改岗位', 'menu_sys_group', 6, null, '', 'sys:group:edit', null, 0, 'sys_module', 201003, null, null, 0, null, null, null, null),
        ('btn_sys_group_list', '岗位列表', 'menu_sys_group', 6, null, '', 'sys:group:page', null, 1, 'sys_module', 201004, null, null, 0, null, null, null, null),
        ('btn_sys_group_detail', '岗位详情', 'menu_sys_group', 6, null, '', 'sys:group:detail', null, 0, 'sys_module', 201005, null, null, 0, null, null, null, null),
        ('btn_sys_group_userList', '岗位用户列表', 'menu_sys_group', 6, null, '', 'sys:group:userList', null, 0, 'sys_module', 201006, null, null, 0, null, null, null, null),
        ('btn_sys_group_addUser', '岗位新增用户', 'menu_sys_group', 6, null, null, 'sys:group:addUser', null, 0, 'sys_module', 201007, null, null, 0, null, null, null, null),
        ('btn_sys_group_deleteUser', '岗位移除用户', 'menu_sys_group', 6, null, null, 'sys:group:deleteUser', null, 0, 'sys_module', 201008, null, null, 0, null, null, null, null),
        ('btn_sys_group_roleList', '岗位角色列表', 'menu_sys_group', 6, null, '', 'sys:group:roleList', null, 0, 'sys_module', 201009, null, null, 0, null, null, null, null),
        ('btn_sys_group_addRole', '岗位新增角色', 'menu_sys_group', 6, null, null, 'sys:group:addRole', null, 0, 'sys_module', 201010, null, null, 0, null, null, null, null),
        ('btn_sys_group_deleteRole', '岗位移除角色', 'menu_sys_group', 6, null, null, 'sys:group:deleteRole', null, 0, 'sys_module', 201011, null, null, 0, null, null, null, null),

        ('btn_sys_role_add', '新增角色', 'menu_sys_role', 6, null, '', 'sys:role:add', null, 0, 'sys_module', 202001, null, null, 0, null, null, null, null),
        ('btn_sys_role_delete', '删除角色', 'menu_sys_role', 6, null, '', 'sys:role:delete', null, 0, 'sys_module', 202002, null, null, 0, null, null, null, null),
        ('btn_sys_role_edit', '修改角色', 'menu_sys_role', 6, null, '', 'sys:role:edit', null, 0, 'sys_module', 202003, null, null, 0, null, null, null, null),
        ('btn_sys_role_list', '角色列表', 'menu_sys_role', 6, null, '', 'sys:role:page', '', 1, 'sys_module', 202004, null, '', 0, null, null, null, null),
        ('btn_sys_role_detail', '角色详情', 'menu_sys_role', 6, null, '', 'sys:role:detail', null, 0, 'sys_module', 202005, null, null, 0, null, null, null, null),
        ('btn_sys_role_userList', '角色用户列表', 'menu_sys_role', 6, null, '', 'sys:role:userList', null, 0, 'sys_module', 202006, null, null, 0, null, null, null, null),
        ('btn_sys_role_addUser', '角色新增用户', 'menu_sys_role', 6, null, null, 'sys:role:addUser', null, 0, 'sys_module', 202007, null, null, 0, null, null, null, null),
        ('btn_sys_role_deleteUser', '角色移除用户', 'menu_sys_role', 6, null, null, 'sys:role:deleteUser', null, 0, 'sys_module', 202008, null, null, 0, null, null, null, null),
        ('btn_sys_role_grantMenu', '授权功能权限', 'menu_sys_role', 6, null, null, 'sys:role:grantMenu', null, 0, 'sys_module', 202009, null, null, 0, null, null, null, null),
        ('btn_sys_role_grantScope', '授权数据权限', 'menu_sys_role', 6, null, null, 'sys:role:grantScope', null, 0, 'sys_module', 202010, null, null, 0, null, null, null, null),

        ('btn_sys_module_add', '新增模块', 'menu_sys_module', 6, null, '', 'sys:resource:add', null, 0, 'sys_module', 301001, null, null, 0, null, null, null, null),
        ('btn_sys_module_delete', '删除模块', 'menu_sys_module', 6, null, '', 'sys:resource:delete', null, 0, 'sys_module', 301002, null, null, 0, null, null, null, null),
        ('btn_sys_module_edit', '修改模块', 'menu_sys_module', 6, null, '', 'sys:resource:edit', null, 0, 'sys_module', 301003, null, null, 0, null, null, null, null),
        ('btn_sys_module_list', '模块列表', 'menu_sys_module', 6, null, '', 'sys:resource:page', null, 1, 'sys_module', 301004, null, null, 0, null, null, null, null),
        ('btn_sys_module_detail', '模块详情', 'menu_sys_module', 6, null, '', 'sys:resource:detail', null, 0, 'sys_module', 301005, null, null, 0, null, null, null, null),

        ('btn_sys_menu_add', '新增菜单', 'menu_sys_menu', 6, null, '', 'sys:resource:add', '', 0, 'sys_module', 302001, null, '', 0, null, null, null, null),
        ('btn_sys_menu_deleteTree', '删除菜单树', 'menu_sys_menu', 6, null, '', 'sys:resource:deleteTree', null, 0, 'sys_module', 302002, null, null, 0, null, null, null, null),
        ('btn_sys_menu_edit', '修改菜单', 'menu_sys_menu', 6, null, '', 'sys:resource:edit', null, 0, 'sys_module', 302003, null, null, 0, null, null, null, null),
        ('btn_sys_menu_tree', '菜单树', 'menu_sys_menu', 6, null, '', 'sys:resource:tree', null, 0, 'sys_module', 302004, null, null, 0, null, null, null, null),
        ('btn_sys_menu_detail', '菜单详情', 'menu_sys_menu', 6, null, '', 'sys:resource:detail', null, 0, 'sys_module', 302005, null, null, 0, null, null, null, null),

        ('btn_sys_api_add', '新增接口', 'menu_sys_api', 6, null, '', 'sys:api:add', null, 0, 'sys_module', 303001, null, null, 0, null, null, null, null),
        ('btn_sys_api_delete', '删除接口', 'menu_sys_api', 6, null, '', 'sys:api:delete', null, 0, 'sys_module', 303002, null, null, 0, null, null, null, null),
        ('btn_sys_api_edit', '修改接口', 'menu_sys_api', 6, null, '', 'sys:api:edit', null, 0, 'sys_module', 303003, null, null, 0, null, null, null, null),
        ('btn_sys_api_list', '接口列表', 'menu_sys_api', 6, null, '', 'sys:api:page', null, 0, 'sys_module', 303004, null, null, 0, null, null, null, null),
        ('btn_sys_api_detail', '接口详情', 'menu_sys_api', 6, null, '', 'sys:api:detail', null, 0, 'sys_module', 303005, null, null, 0, null, null, null, null),

        ('btn_sys_session_delete', '强制退出', 'menu_sys_session', 6, null, '', 'auth:session:delete', null, 0, 'sys_module', 500202, null, null, 0, null, null, null, null),
        ('btn_sys_session_deleteToken', '强退令牌', 'menu_sys_session', 6, null, '', 'auth:session:deleteToken', null, 0, 'sys_module', 500204, null, null, 0, null, null, null, null),
        ('btn_sys_session_renewActive', '续签令牌', 'menu_sys_session', 6, null, '', 'auth:session:renewActive', null, 0, 'sys_module', 500206, null, null, 0, null, null, null, null),
        ('btn_sys_session_list', '会话列表', 'menu_sys_session', 6, null, '', 'auth:session:page', null, 0, 'sys_module', 500208, null, null, 0, null, null, null, null),
        ('btn_sys_session_tokenList', '令牌列表', 'menu_sys_session', 6, null, '', 'auth:session:tokenList', null, 0, 'sys_module', 500210, null, null, 0, null, null, null, null),
        ('btn_sys_resource_list', '资源列表', 'menu_sys_resource', 6, null, '', 'sys:resource:list', null, 0, 'sys_module', 304001, null, null, 0, null, null, null, null),

        ('btn_biz_org_add', '新增机构', 'menu_biz_org', 6, null, null, null, null, 0, 'biz_module', 511001, null, '', 0, null, null, null, null),
        ('btn_biz_org_del', '删除机构', 'menu_biz_org', 6, null, null, null, null, 0, 'biz_module', 511002, null, '', 0, null, null, null, null),
        ('btn_biz_org_edit', '编辑机构', 'menu_biz_org', 6, null, null, null, null, 0, 'biz_module', 511003, null, '', 0, null, null, null, null);

-- 接口数据
insert into moyu.sys_api (code, name, path, has_scope, api_type, ext_json, remark, deleted, create_time, create_by, update_time, update_by)
values ('sys:org:tree', '组织树', '/api/sys/org/tree', 1, 1, null, null, 0, null, null, null, null),
       ('sys:org:add', '新增组织', '/api/sys/org/add', 0, 1, null, null, 0, null, null, null, null),
       ('sys:org:delete', '删除组织', '/api/sys/org/delete', 0, 1, null, null, 0, null, null, null, null),
       ('sys:org:edit', '修改组织', '/api/sys/org/edit', 0, 1, null, null, 0, null, null, null, null),
       ('sys:org:page', '组织列表', '/api/sys/org/page', 1, 1, null, null, 0, null, null, null, null),
       ('sys:org:detail', '组织详情', '/api/sys/org/detail', 0, 1, null, null, 0, null, null, null, null),
       ('sys:org:deleteTree', '删除组织树', '/api/sys/org/deleteTree', 0, 1, null, null, 0, null, null, null, null),
       ('sys:user:add', '新增用户', '/api/sys/user/add', 0, 1, null, null, 0, null, null, null, null),
       ('sys:user:delete', '删除用户', '/api/sys/user/delete', 0, 1, null, null, 0, null, null, null, null),
       ('sys:user:edit', '修改用户', '/api/sys/user/add', 0, 1, null, null, 0, null, null, null, null),
       ('sys:user:page', '用户列表', '/api/sys/user/page', 1, 1, null, null, 0, null, null, null, null),
       ('sys:user:detail', '用户详情', '/api/sys/user/detail', 0, 1, null, null, 0, null, null, null, null),
       ('sys:group:add', '新增岗位', '/api/sys/group/add', 0, 1, null, null, 0, null, null, null, null),
       ('sys:group:delete', '删除岗位', '/api/sys/group/delete', 0, 1, null, null, 0, null, null, null, null),
       ('sys:group:edit', '修改岗位', '/api/sys/group/add', 0, 1, null, null, 0, null, null, null, null),
       ('sys:group:page', '岗位列表', '/api/sys/group/page', 1, 1, null, null, 0, null, null, null, null),
       ('sys:group:detail', '岗位详情', '/api/sys/group/detail', 0, 1, null, null, 0, null, null, null, null),
       ('sys:group:userList', '岗位用户列表', '/api/sys/group/userList', 0, 1, null, null, 0, null, null, null, null),
       ('sys:group:addUser', '岗位新增用户', '/api/sys/group/addUser', 0, 1, null, null, 0, null, null, null, null),
       ('sys:group:deleteUser', '岗位移除用户', '/api/sys/group/deleteUser', 0, 1, null, null, 0, null, null, null, null),
       ('sys:group:roleList', '岗位角色列表', '/api/sys/group/roleList', 0, 1, null, null, 0, null, null, null, null),
       ('sys:group:addRole', '岗位新增角色', '/api/sys/group/addRole', 0, 1, null, null, 0, null, null, null, null),
       ('sys:group:deleteRole', '岗位移除角色', '/api/sys/group/deleteRole', 0, 1, null, null, 0, null, null, null, null),
       ('sys:role:add', '新增角色', '/api/sys/role/add', 0, 1, null, null, 0, null, null, null, null),
       ('sys:role:delete', '删除角色', '/api/sys/role/delete', 0, 1, null, null, 0, null, null, null, null),
       ('sys:role:edit', '修改角色', '/api/sys/role/add', 0, 1, null, null, 0, null, null, null, null),
       ('sys:role:page', '角色列表', '/api/sys/role/page', 1, 1, null, null, 0, null, null, null, null),
       ('sys:role:detail', '角色详情', '/api/sys/role/detail', 0, 1, null, null, 0, null, null, null, null),
       ('sys:role:userList', '角色用户列表', '/api/sys/role/userList', 0, 1, null, null, 0, null, null, null, null),
       ('sys:role:addUser', '角色新增用户', '/api/sys/role/addUser', 0, 1, null, null, 0, null, null, null, null),
       ('sys:role:deleteUser', '角色移除用户', '/api/sys/role/deleteUser', 0, 1, null, null, 0, null, null, null, null),
       ('sys:role:grantMenu', '授权功能权限', '/api/sys/role/grantMenu', 0, 1, null, null, 0, null, null, null, null),
       ('sys:role:grantScope', '授权数据权限', '/api/sys/role/grantScope', 0, 1, null, null, 0, null, null, null, null),
       ('sys:resource:add', '新增菜单', '/api/sys/resource/add', 0, 1, null, null, 0, null, null, null, null),
       ('sys:resource:delete', '删除菜单', '/api/sys/resource/delete', 0, 1, null, null, 0, null, null, null, null),
       ('sys:resource:deleteTree', '删除菜单树', '/api/sys/resource/deleteTree', 0, 1, null, null, 0, null, null, null, null),
       ('sys:resource:edit', '修改菜单', '/api/sys/resource/edit', 0, 1, null, null, 0, null, null, null, null),
       ('sys:resource:page', '菜单列表', '/api/sys/resource/page', 0, 1, null, null, 0, null, null, null, null),
       ('sys:resource:detail', '菜单详情', '/api/sys/resource/detail', 0, 1, null, null, 0, null, null, null, null),
       ('sys:resource:tree', '菜单树', '/api/sys/resource/tree', 0, 1, null, null, 0, null, null, null, null),
       ('sys:resource:list', '资源列表', '/api/sys/resource/list', 0, 1, null, null, 0, null, null, null, null),
       ('auth:session:delete', '强制退出', '/api/auth/session/delete', 0, 1, null, null, 0, null, null, null, null),
       ('auth:session:deleteToken', '强退令牌', '/api/auth/session/deleteToken', 0, 1, null, null, 0, null, null, null, null),
       ('auth:session:renewActive', '续签令牌', '/api/auth/session/renewActive', 0, 1, null, null, 0, null, null, null, null),
       ('auth:session:page', '会话列表', '/api/auth/session/page', 0, 1, null, null, 0, null, null, null, null),
       ('auth:session:tokenList', '令牌列表', '/api/auth/session/tokenList', 0, 1, null, null, 0, null, null, null, null);

-- 关系
INSERT INTO moyu.sys_relation (object_id, target_id, relation_type, ext_json, deleted, create_time, create_by, update_time, update_by)
VALUES  ('rAdmin', 'ROOT', 1, null, 0, null, null, null, null),
        ('superAdmin', 'r_superAdmin', 1, null, 0, null, null, null, null),

        ('r_default', 'menu_sys_org', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_user', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_group', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_role', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_module', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_menu', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_api', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_resource', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_gen', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_session', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_gen', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_config', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_vislog', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_oplog', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_sys_log', 2, null, 0, null, null, null, null),
        ('r_default', 'menu_biz_pos', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_user_list', 2, '{"dataScope":2}', 0, null, null, null, null),
        ('r_default', 'btn_sys_user_detail', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_role_userList', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_role_list', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_role_detail', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_org_list', 2, '{"dataScope":2}', 0, null, null, null, null),
        ('r_default', 'api_sys_org_tree', 2, '{"dataScope":2}', 0, null, null, null, null),
        ('r_default', 'btn_sys_org_detail', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_module_list', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_module_detail', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_menu_tree', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_menu_detail', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_group_userList', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_group_roleList', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_group_list', 2, '{"dataScope":2}', 0, null, null, null, null),
        ('r_default', 'btn_sys_group_detail', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_api_list', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_api_detail', 2, null, 0, null, null, null, null),
        ('r_default', 'btn_sys_session_list', 2, null, 0, null, null, null, null),

        ('r_superAdmin', 'menu_sys_org', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_user', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_group', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_role', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_module', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_menu', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_api', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_gen', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'iframe_sys_link', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'link_sys_doc', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_session', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_log', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_vislog', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_sys_oplog', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'menu_biz_pos', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_user_list', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_user_detail', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_role_userList', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_role_list', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_role_detail', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_org_list', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_org_detail', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_module_list', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_module_detail', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_menu_tree', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_menu_detail', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_group_userList', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_group_roleList', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_group_list', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_group_detail', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_api_list', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_api_detail', 2, null, 0, null, null, null, null),
        ('r_superAdmin', 'btn_sys_session_list', 2, null, 0, null, null, null, null),

        ('r_roleAdmin', 'menu_sys_role', 2, null, 0, null, null, null, null),
        ('r_roleAdmin', 'btn_sys_role_add', 2, null, 0, null, null, null, null),
        ('r_roleAdmin', 'btn_sys_role_delete', 2, null, 0, null, null, null, null),
        ('r_roleAdmin', 'btn_sys_role_edit', 2, null, 0, null, null, null, null),
        ('r_roleAdmin', 'btn_sys_role_list', 2, null, 0, null, null, null, null),
        ('r_roleAdmin', 'btn_sys_role_detail', 2, null, 0, null, null, null, null),
        ('r_roleAdmin', 'btn_sys_role_userList', 2, null, 0, null, null, null, null),
        ('r_roleAdmin', 'btn_sys_role_addUser', 2, null, 0, null, null, null, null),
        ('r_roleAdmin', 'btn_sys_role_deleteUser', 2, null, 0, null, null, null, null),
        ('r_roleAdmin', 'btn_sys_role_grantMenu', 2, null, 0, null, null, null, null),
        ('r_roleAdmin', 'btn_sys_role_grantScope', 2, null, 0, null, null, null, null),

        ('r_orgAdmin', 'menu_sys_org', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'menu_sys_user', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'menu_sys_group', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_user_list', 2, '{"dataScope":4}', 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_user_detail', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'api_sys_org_tree', 2, '{"dataScope":4}', 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_org_list', 2, '{"dataScope":4}', 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_org_detail', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_add', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_delete', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_edit', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_detail', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_list', 2, '{"dataScope":4}', 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_userList', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_addUser', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_deleteUser', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_roleList', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_addRole', 2, null, 0, null, null, null, null),
        ('r_orgAdmin', 'btn_sys_group_deleteRole', 2, null, 0, null, null, null, null),

        ('r_auditor', 'menu_sys_org', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_sys_user', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_sys_group', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_sys_role', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_sys_module', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_sys_menu', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_sys_api', 2, null, 0, null, null, null, null),
        ('r_auditor', 'iframe_sys_link', 2, null, 0, null, null, null, null),
        ('r_auditor', 'link_sys_doc', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_sys_log', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_sys_vislog', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_sys_oplog', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_biz_pos', 2, null, 0, null, null, null, null),
        ('r_auditor', 'menu_biz_notice', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_user_list', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_user_detail', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_role_userList', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_role_list', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_role_detail', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_org_list', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_org_detail', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_module_list', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_module_detail', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_menu_tree', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_menu_detail', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_group_userList', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_group_roleList', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_group_list', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_group_detail', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_api_list', 2, null, 0, null, null, null, null),
        ('r_auditor', 'btn_sys_api_detail', 2, null, 0, null, null, null, null),

        ('bjAdmin', 'g_zongbu', 3, null, 0, null, null, null, null),
        ('r_orgAdmin', 'g_zongbu', 4, null, 0, null, null, null, null),
        ('bjAdmin', 'g_beijing', 3, null, 0, null, null, null, null),
        ('auditor', 'g_auditor', 3, null, 0, null, null, null, null),
        ('g_beijing', 'r_orgAdmin', 4, null, 0, null, null, null, null),
        ('g_auditor', 'r_auditor', 4, null, 0, null, null, null, null);

